### PR TITLE
Change .value to [()] for h5py datasets.

### PR DESCRIPTION
**Pull request by vijayvarma392**
.value has already been deprecated in the latest h5py versions.

### CODE REVIEW

**Comment by vijayvarma392** [comment]
@jblackma: Can you merge this when you get a chance? This should help with future-proofing.

**Comment by jblackma** [comment]
Lgtm

**Comment by vijayvarma392** [comment]
Thanks! If you still remember your pypi password, can you please update that as well? :)

**Comment by jblackma** [comment]
I am able to log in to pypi but am unable to update the repo at the moment.
Happy to add you as a collaborator to the pypi project or I'll get to this
over the weekend.

**Comment by vijayvarma392** [comment]
Sure, whichever way is easier for you is fine. Not super urgent. My pypi username is vijayvarma.

**Comment by jblackma** [comment]
What's your pypi username?

**Comment by vijayvarma392** [comment]
vijayvarma

**Comment by jblackma** [comment]
Invite sent

**Comment by vijayvarma392** [comment]
Got it, thanks! Actually, could you give me write access to this repo as well? I would need to update the version, etc, and it would need another PR :)

**Pull request merged**
